---
# Default cf-deployment deploys a (mostly) HA configuration.
# Use this override to only deploy single instance of each job,
# in a single Availability Zone.
- type: replace
  path: /instance_groups/name=all-in-one-1/instances
  value: 1

- type: replace
  path: /instance_groups/name=all-in-one-1/azs
  value: [ z1 ]
