- type: replace
  path: /vm_extensions/-
  value:
    name: vmss_properties
    cloud_properties:
      vmss:
        availability_zones: ['1','2']

# - type: replace
#   path: /vm_extensions/-
#   value:
#     name: cf-router-network-properties
#     cloud_properties:
#       load_balancer: ((cf_loadbalancer_name))

# - type: replace
#   path: /vm_extensions/-
#   value:
#     name: cf-tcp-router-network-properties

- type: replace
  path: /vm_types/-
  value:
    name: lite
    cloud_properties:
      ephemeral_disk:
        size: 10240
      instance_type: Standard_A1_v2

- type: replace
  path: /networks/-
  value:
    name: cfcr
    subnets:
    - azs:
      - z1
      - z2
      - z3
      gateway: ((cfcr_internal_gw))
      range: ((cfcr_subnet_cidr))
      reserved:
      - ((cfcr_internal_gw))/30
      # dns:
      # - 8.8.8.8
      # - 168.63.129.16
      cloud_properties:
        virtual_network_name: ((vnet_name))
        subnet_name: ((cfcr_subnet))
        # security_group: ((cfcr_security_group))
    type: dynamic