---
- path: /releases/name=bosh/url
  type: replace
  value: https://mirror.azure.cn/bosh/bosh-compiled-release-tarballs/bosh-266.5.0-ubuntu-trusty-3586.24-20180627-220754-534204036-20180627220759.tgz
- type: replace
  path: /resource_pools/name=vms/stemcell/url
  value: https://mirror.azure.cn/bosh/bosh-azure-stemcells/bosh-stemcell-3586.24-azure-hyperv-ubuntu-trusty-go_agent.tgz
- path: /releases/name=os-conf/url
  type: replace
  value: https://mirror.azure.cn/bosh/os-conf/os-conf-release-18.tgz
